### ISSUE TITLE
Migrate to Dio

### ISSUE THREAD

**Issue by vrrao01** [vrrao01/onestop_dev#217]
### Summary

Currently both `http` and `dio` packages are being used to handle network requests. Migrate the entire project to `dio`. Will be helpful when setting up token based auth for the entire app in the future. 

### Issue Assignment

No

**Comment by Hareesh-Nandigrama** [comment]
![image](https://user-images.githubusercontent.com/85237630/224525549-85857b33-8458-4955-a9ff-3e499aae3066.png)

**Comment by Hareesh-Nandigrama** [comment]
@vrrao01 bhaiya yeh toh discontinue hone wala hai apparently

**Comment by vrrao01** [comment]
@Hareesh-Nandigrama Let's not use it phir. Joh abhi Dio use hua hai UPSP mein, HTTP mein convert karte
